name: Deploy to REG.RU

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP to REG.RU
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/vladgalanov.ru/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            README.md
            package.json
            package-lock.json
            .DS_Store
            .env
            .env.local
